book/urls.py
from django.urls import path
from book.views import get_books

app_name = 'book'
urlpatterns = [
    path("", get_books, name="get_books"),
]

fitur_premium/urls.py
from django.urls import path
from fitur_premium.views import get_ruangan_json, show_main, index_premium, get_buku_premium, baca, add_sewa_buku_ajax
app_name = 'fitur_premium'

urlpatterns = [
    path('', index_premium, name='index_premium'),
    path('sewa-buku-ajax/', add_sewa_buku_ajax, name='add_sewa_buku'),
    path('sewa_ruangan', show_main, name="show_main"),
    path("get_buku_premium/", get_buku_premium, name="get_buku_premium"),
    path("baca/<int:id>", baca, name="baca"),
    path("get_ruangan_json/", get_ruangan_json, name="get_ruangan_json")
]

pustaring/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/books/', include("book.urls")),
    path('sistem_manajemen/', include("sistem_manajemen.urls")),
    path('fitur_premium/', include("fitur_premium.urls")),
    path('customer_service/', include("customer_service.urls")),
    path('', include("beranda.urls")),
    path('ulasan/', include("ulasan.urls")),
    path('peminjaman_buku/', include("peminjaman_buku.urls")),
    path('auth/', include('authentication.urls')),
]

sistem_manajemen/urls.py
from django.urls import path
from sistem_manajemen.views import show_sistem, get_ruangan_json, add_ruangan_ajax, show_sistem_ruangan, show_sistem_buku, get_buku_json, ganti_status_ketersediaan, show_peminjaman, get_peminjaman_json, ganti_status_peminjaman, ganti_status_ketersediaan_buku, create_ruangan_flutter

app_name = 'sistem_manajemen'

urlpatterns = [
    path("", show_sistem, name="show_sistem"),
    path('get-ruangan/', get_ruangan_json, name='get_ruangan_json'),
    path('create-ruangan-ajax/', add_ruangan_ajax, name='add_ruangan_ajax'),
    path('sistem_ruangan', show_sistem_ruangan, name="sistem_ruangan"),
    path('sistem_buku', show_sistem_buku, name="sistem_buku"),
    path('get_buku_json/<str:id>', get_buku_json, name="get_buku_json"),
    path('edit_ketersediaan/<int:id>', ganti_status_ketersediaan, name='edit_ketersediaan'),
    path('peminjaman/', show_peminjaman, name="show_peminjaman"),
    path('get-peminjaman/', get_peminjaman_json, name='get_peminjaman_json'),
    path('edit_peminjaman/<int:id>', ganti_status_peminjaman, name='edit_peminjaman'),
    path('edit_ketersediaan_buku/<int:id>', ganti_status_ketersediaan_buku, name='edit_ketersediaan_buku'),
    path('create-flutter/', create_ruangan_flutter, name='create_ruangan_flutter'),
]

fitur_premium/models.py
from django.db import models


# Create your models here.

class fitur_premium(models.Model):
    title = models.TextField(null=True, blank=True)
    jumlah_hari = models.TextField(null=True, blank=True)
    id_user = models.TextField(null=True, blank=True)

fitur_premium/views.py
from django.shortcuts import render
from sistem_manajemen.models import Ruangan
from book.models import Book
from fitur_premium.models import fitur_premium
from django.http import HttpResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound

# Create your views here.
def get_ruangan_json(request):
    book = Ruangan.objects.filter(ketersediaan="tersedia")
    return HttpResponse(serializers.serialize('json', book))

def get_buku_premium(request):
    book = Book.objects.filter(vip="vip")
    return HttpResponse(serializers.serialize('json', book))

def baca(request,id):
    book = Book.objects.get(id=id)
    return render(request,'baca.html',{'book' : book})


def show_main(request):
    context = {
    }
    return render(request, "sewa_ruangan.html", context)

def index_premium(request):
    data_ruangan = Ruangan.objects.all()
    for dr in  data_ruangan:
        print(data_ruangan)
    return render(request,'index_premium.html',{'ruangan' : data_ruangan})    

@csrf_exempt
def add_sewa_buku_ajax(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        jumlah_hari = request.POST.get("jumlah_hari")

        new_sewa_buku = fitur_premium(title=title, jumlah_hari=jumlah_hari)
        new_sewa_buku.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()  

fitur_premium/templates/baca.html
{% extends 'base.html' %}

{% block content %}


<div class="container mt-5">
        <div class="container bg-success" style="margin-bottom:50px; margin-top:50px; padding:20px;">
            <h1 class="text-center text-white">{{ book.title  }}</h1>
        </div>
        <div class="card">
            <div class="card-header">
                <h1 class="card-title">Summary</h1>
            </div>
            <div class="card-body">
                <p>{{ book.summary }}</p>
            </div>
            <div class="card-footer">
                <a href="{% url 'fitur_premium:index_premium' %}" class="btn btn-primary btn-block mt-3">Kembali</a>
            </div>
        </div>
</div>



{% endblock content %}

fitur_premium/templates/index_premium.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="container bg-success" style="margin-bottom:20px; margin-top:50px; padding:20px;">
            <h1 class="text-center text-white">Beranda Premium</h1>
        </div>
    <!-- Button trigger modal -->
          
        <div class="card">
            <div class="card-header">
                <h1 class="card-title">Nikmati Akses Buku VIP</h1>
            </div>
            <div class="card-body">
                <table class="table" id="buku_table">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Genre</th>
                            <th>Sewa</th>
                            <th>#</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Data will be inserted here dynamically -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="container mt-5">
        <div class="card">
            <div class="card-header">
                <h1 class="card-title">Buku lainnya yang bisa anda baca</h1>
            </div>
            <div class="card-body">
                <table class="table" id="buku_free">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Genre</th>
                            <th>Sewa</th>
                            <th>#</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Data will be inserted here dynamically -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>



    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Sewa Ruangan</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <div class="form-group">
                <label for="">Ruangan</label>
                <select name="" id="" class="form-control">
                    {{ data_ruangan }}
                </select>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
    </div>

    <div class="modal fade" id="sewa" tabindex="-1" aria-labelledby="sewaLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="sewaLabel">Sewa Buku</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="form" onsubmit="return false;">
            {% csrf_token %}
            <div class="modal-body">
              <input type="hidden" id="title" name="title" >
              <div class="form-group">
                <label for="">Jumlah Hari</label>
                <select name="jumlah_hari" id="" class="form-control">
                    <option value="1">1 Hari</option>
                    <option value="2">2 Hari</option>
                </select>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
            </form>
          </div>
        </div>
    </div>


    <script>
        async function getBookPremium() {
            return fetch("{% url 'fitur_premium:get_buku_premium' %}").then((res) => res.json());
        }

        async function getFree() {
            return fetch("{% url 'sistem_manajemen:get_ruangan_json' %}").then((res) => res.json())
        }

        async function refreshPremium() {
            const tableBody = document.querySelector("#buku_table tbody");
            tableBody.innerHTML = "";

            const products = await getBookPremium();

            products.forEach((item) => {
                const row = document.createElement("tr");
                row.innerHTML = `
                    <td>${item.fields.title}</td>
                    <td>${item.fields.genre}</td>
                    <td><button class="btn btn-warning sewa" data-title="${item.fields.title}" data-id="${item.pk}">Sewa</button> </td>
                    <td> <a href="baca/${item.pk}" class="btn btn-primary btn-block">Baca</a> </td>
                `;
                tableBody.appendChild(row);
            });
            $('.sewa').on('click',function(){
                let title = $(this).data("title");
                $('#title').val(title);
                $('#sewa').modal('toggle');
            });
        }

        async function refreshFreeBook() {
            const tableBody = document.querySelector("#buku_free tbody");
            tableBody.innerHTML = "";

            const products = await getBookPremium();

            products.forEach((item) => {
                const row = document.createElement("tr");
                row.innerHTML = `
                    <td>${item.fields.title}</td>
                    <td>${item.fields.genre}</td>
                    <td><button class="btn btn-warning sewa" data-title="${item.fields.title}" data-id="${item.pk}">Sewa</button> </td>
                    <td> <a href="baca/${item.pk}" class="btn btn-primary btn-block">Baca</a> </td>
                `;
                tableBody.appendChild(row);
            });
            $('.sewa').on('click',function(){
                let title = $(this).data("title");
                $('#title').val(title);
                $('#sewa').modal('toggle');
            });
        }

        refreshFreeBook();
        refreshPremium();
    </script>
    <script>
    $(document).ready(function () {

        $('#form').on('submit',function(){
            fetch("{% url 'fitur_premium:add_sewa_buku' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshFreeBook)

            document.getElementById("form").reset();
            location.reload();
            return false;
        });

        
    });
    </script>
{% endblock content %}

fitur_premium/templates/sewa_ruangan.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">List Ruangan Yang Tersedia</h1>
                <table class="table" id="ruangan_table">
                    <!-- Table data will be inserted here -->
                </table>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="nomor" class="col-form-label">Nomor:</label>
                            <input type="text" class="form-control" id="nomor" name="nomor"></input>
                        </div>
                        <div class="mb-3">
                            <label for="ketersediaan" class="col-form-label">Ketersediaan:</label>
                            <input type="text" class="form-control" id="ketersediaan" name="ketersediaan"></input>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        async function getProducts() {
            return fetch("{% url 'fitur_premium:get_ruangan_json' %}").then((res) => res.json())
        }
        async function refreshProducts() {
            const table = document.getElementById("ruangan_table");
            table.innerHTML = "";
            const products = await getProducts();
            let htmlString = `<thead>
                <tr>
                    <th>Nomor</th>
                    <th>Ketersediaan</th>
                </tr>
                </thead>
                <tbody>`;

            products.forEach((item) => {
                htmlString += `<tr>
                    <td>${item.fields.nomor}</td>
                    <td>${item.fields.ketersediaan}</td>
                </tr>`;
            });

            htmlString += `</tbody>`;
            table.innerHTML = htmlString;
        }

        refreshProducts();
    </script>
{% endblock content %}