beranda/urls.py
from django.urls import path
from beranda.views import *

app_name = 'beranda'
urlpatterns = [
    path('', show_beranda, name='show_beranda'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path('peminjaman_buku/', show_peminjaman_buku, name='show_peminjaman_buku'),


]

book/urls.py
from django.urls import path
from book.views import get_books

app_name = 'book'
urlpatterns = [
    path("", get_books, name="get_books"),
]

pustaring/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/books/', include("book.urls")),
    path('sistem_manajemen/', include("sistem_manajemen.urls")),
    path('fitur_premium/', include("fitur_premium.urls")),
    path('customer_service/', include("customer_service.urls")),
    path('', include("beranda.urls")),
    path('ulasan/', include("ulasan.urls")),
    path('peminjaman_buku/', include("peminjaman_buku.urls")),
    path('auth/', include('authentication.urls')),
]

sistem_manajemen/urls.py
from django.urls import path
from sistem_manajemen.views import show_sistem, get_ruangan_json, add_ruangan_ajax, show_sistem_ruangan, show_sistem_buku, get_buku_json, ganti_status_ketersediaan, show_peminjaman, get_peminjaman_json, ganti_status_peminjaman, ganti_status_ketersediaan_buku, create_ruangan_flutter

app_name = 'sistem_manajemen'

urlpatterns = [
    path("", show_sistem, name="show_sistem"),
    path('get-ruangan/', get_ruangan_json, name='get_ruangan_json'),
    path('create-ruangan-ajax/', add_ruangan_ajax, name='add_ruangan_ajax'),
    path('sistem_ruangan', show_sistem_ruangan, name="sistem_ruangan"),
    path('sistem_buku', show_sistem_buku, name="sistem_buku"),
    path('get_buku_json/<str:id>', get_buku_json, name="get_buku_json"),
    path('edit_ketersediaan/<int:id>', ganti_status_ketersediaan, name='edit_ketersediaan'),
    path('peminjaman/', show_peminjaman, name="show_peminjaman"),
    path('get-peminjaman/', get_peminjaman_json, name='get_peminjaman_json'),
    path('edit_peminjaman/<int:id>', ganti_status_peminjaman, name='edit_peminjaman'),
    path('edit_ketersediaan_buku/<int:id>', ganti_status_ketersediaan_buku, name='edit_ketersediaan_buku'),
    path('create-flutter/', create_ruangan_flutter, name='create_ruangan_flutter'),
]

sistem_manajemen/models.py
from django.db import models

class Ruangan(models.Model):
    nomor = models.IntegerField()
    ketersediaan = models.CharField(max_length=255)

sistem_manajemen/forms.py
from django import forms
from .models import Ruangan  # Import your Ruangan model

class RuanganForm(forms.ModelForm):
    class Meta:
        model = Ruangan  # Use your Ruangan model
        fields = ['nomor', 'ketersediaan']  # Define the fields you want in your form

sistem_manajemen/views.py
from django.shortcuts import render
from sistem_manajemen.models import Ruangan
from django.http import HttpResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound
from book.models import Book
from peminjaman_buku.models import PinjamBuku
from django.http import HttpResponseNotFound
from django.http import HttpResponseRedirect
from django.urls import reverse
from sistem_manajemen.forms import RuanganForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import json

# Create your views here.
@login_required(login_url='/login')
def show_sistem(request):
    if(request.user.username.split("-")[-1] != "pekerja"):
        return HttpResponse(b"Restricted")
    context = {
        'name':request.user.username,
    }

    return render(request, "main.html", context)

@login_required(login_url='/login')
def show_sistem_ruangan(request):
    if(request.user.username.split("-")[-1] != "pekerja"):
        return HttpResponse(b"Restricted")
    ruangan = Ruangan.objects.all()
    form = RuanganForm(request.POST)
    context = {
        'products':ruangan,
        'form': form,
        'name':request.user.username,
    }
    return render(request, "sistem_manajemen.html", context)

@login_required(login_url='/login')
def show_sistem_buku(request):
    if(request.user.username.split("-")[-1] != "pekerja"):
        return HttpResponse(b"Restricted")
    context = {
        'name':request.user.username,
    }
    return render(request, "manage_buku.html", context)

def get_buku_json(request, id):
    if(id == "tidak_ada_filter") :
        book = Book.objects.all()
    else :
        book = Book.objects.filter(genre=id)
    return HttpResponse(serializers.serialize('json', book))

def get_ruangan_json(request):
    ruangan = Ruangan.objects.all()
    return HttpResponse(serializers.serialize('json', ruangan))

#@csrf_exempt
def add_ruangan_ajax(request):
    if request.method == 'POST':
        form = RuanganForm(request.POST)
        if form.is_valid() and request.method == "POST":
            form.save()
            return HttpResponse(b"CREATED", status=201)
        

    return HttpResponseNotFound()

def ganti_status_ketersediaan(request, id):
    ruangan = Ruangan.objects.get(pk=id)
    if(ruangan.ketersediaan == "tersedia") :
        ruangan.ketersediaan = "disewa"
    else:
        ruangan.ketersediaan = "tersedia"
    ruangan.save()
    return HttpResponseRedirect(reverse('sistem_manajemen:sistem_ruangan'))

@login_required(login_url='/login')
def show_peminjaman(request):
    if(request.user.username.split("-")[-1] != "pekerja"):
        return HttpResponse(b"Restricted")
    peminjaman = PinjamBuku.objects.all()
    context = {
        'products':peminjaman,
        'name':request.user.username,
    }
    return render(request, "peminjaman_manajemen.html", context)

def get_peminjaman_json(request):
    pinjam = PinjamBuku.objects.all()
    return HttpResponse(serializers.serialize('json', pinjam))

def ganti_status_peminjaman(request, id):
    pinjam = PinjamBuku.objects.get(pk=id)
    pinjam.status_acc = True
    pinjam.save()
    return HttpResponseRedirect(reverse('sistem_manajemen:show_peminjaman'))

def ganti_status_ketersediaan_buku(request, id):
    buku = Book.objects.get(pk=id)
    if(buku.ketersediaan == "tersedia") :
        buku.ketersediaan = "dipinjam"
    else:
        buku.ketersediaan = "tersedia"
    buku.save()
    return HttpResponseRedirect(reverse('sistem_manajemen:sistem_buku'))

@csrf_exempt
def create_ruangan_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Ruangan.objects.create(
            nomor = int(data["nomor"]),
            ketersediaan = data["ketersediaan"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

sistem_manajemen/templates/main.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">Selamat Datang {{name}} di System Managemen</h1>
                <div class="card">
                    <div class="card-body">
                        <a href="{% url 'sistem_manajemen:sistem_ruangan' %}" class="btn btn-primary btn-block mt-3">Manage Ruangan</a>
                        <p class="card-text">Kelola informasi tentang ruangan.</p>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <a href="{% url 'sistem_manajemen:sistem_buku' %}" class="btn btn-primary btn-block mt-3">Manage Buku</a>
                        <p class="card-text">Kelola informasi tentang buku.</p>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <a href="{% url 'sistem_manajemen:show_peminjaman' %}" class="btn btn-primary btn-block mt-3">Manage Peminjaman</a>
                        <p class="card-text">Terima Request Peminjaman</p>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">    
						<a href="{% url 'beranda:logout' %}" >  
							<button class="btn btn-primary btn-block mt-3">
								Logout	
							</button>
						</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

sistem_manajemen/templates/manage_buku.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-header">
                <h1 class="card-title">Selamat Datang di Manage Buku</h1>
                <select id="myDropdown">
				  <option value="tidak_ada_filter" selected>Silahkan Pilih Filter</option>
				  <option value="fantasy">fantasy</option>
				  <option value="science">science</option>
				  <option value="crime">crime</option>
				  <option value="history">history</option>
				  <option value="horror">horror</option>
				  <option value="thriller">thriller</option>
				  <option value="psychology">psychology</option>
				  <option value="romance">romance</option>
				  <option value="sports">sports</option>
				  <option value="travel">travel</option>
				</select>
				<button type="button" class="btn btn-primary" id="button_filter" data-bs-dismiss="modal">Filter</button>
            </div>
            <div class="card-body">
                <table class="table" id="buku_table">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Genre</th>
                            <th>Ketersediaan</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Data will be inserted here dynamically -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script>
        async function getProducts(hasil_filter) {
			const baseUrl = "{% url 'sistem_manajemen:get_buku_json' 0 %}";
            return fetch(`${baseUrl.replace('0', hasil_filter)}`).then((res) => res.json());
        }
        async function refreshProducts() {
			const baseurl = "{% url 'sistem_manajemen:edit_ketersediaan_buku' 0 %}";
            const tableBody = document.querySelector("#buku_table tbody");
            tableBody.innerHTML = "";
            let dropdown = document.getElementById("myDropdown");
            let filter = "tidak_ada_filter";
			filter = dropdown.value;
            const products = await getProducts(filter);

            products.forEach((item) => {
                const row = document.createElement("tr");
                row.innerHTML = `
                    <td>${item.fields.title}</td>
                    <td>${item.fields.genre}</td>
                    <td>${item.fields.ketersediaan}</td>
                    <td>
						<a href="${baseurl.replace('0', item.pk)}">
							<button class="btn btn-primary">
								Ganti Status
							</button>
						</a>
					</td>
                `;
                tableBody.appendChild(row);
            });
        }
        refreshProducts();
        document.getElementById("button_filter").onclick = refreshProducts;
    </script>
{% endblock content %}

sistem_manajemen/templates/peminjaman_manajemen.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">List Peminjaman</h1>
                <table class="table" id="ruangan_table">
                    <!-- Table data will be inserted here -->
                </table>
            </div>
        </div>
    </div>

   
   
    <script>
        async function getProducts() {
            return fetch("{% url 'sistem_manajemen:get_peminjaman_json' %}").then((res) => res.json())
        }
        const baseUrl = "{% url 'sistem_manajemen:edit_peminjaman' 0 %}";
        async function refreshProducts() {
            const table = document.getElementById("ruangan_table");
            table.innerHTML = "";
            const products = await getProducts();
            let htmlString = `<thead>
                <tr>
					<th>Judul  buku</th>
                    <th>Tanggal Pinjam</th>
                    <th>Tanggal Pembelian</th>
                    <th>Status Penerimaan</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>`;

            products.forEach((item) => { 
				const text = item.fields.buku;
                htmlString += `<tr>
					<td>${item.fields.buku}</td>
					<td>${item.fields.tanggal_peminjaman}</td>
                    <td>${item.fields.tanggal_pengembalian}</td>
                    <td>${item.fields.status_acc}</td>
                    <td>
						<a href="${baseUrl.replace('0', item.pk)}">
							<button class="btn btn-primary">
								Terima
							</button>
						</a>
					</td>
                </tr>`;
            });

            htmlString += `</tbody>`;
            table.innerHTML = htmlString;
        }

        refreshProducts();
        
    </script>
{% endblock content %}

sistem_manajemen/templates/sistem_manajemen.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">List Ruangan</h1>
                <table class="table" id="ruangan_table">
                    <!-- Table data will be inserted here -->
                </table>
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Tambah Ruangan</button>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Tambahkan Ruangan</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
						{% csrf_token %}
						{{ form.nomor.label_tag }} {{ form.nomor }}<br>
						{{ form.ketersediaan.label_tag }} {{ form.ketersediaan }}<br>
					</form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        async function getProducts() {
            return fetch("{% url 'sistem_manajemen:get_ruangan_json' %}").then((res) => res.json())
        }
        const baseUrl = "{% url 'sistem_manajemen:edit_ketersediaan' 0 %}";
        async function refreshProducts() {
            const table = document.getElementById("ruangan_table");
            table.innerHTML = "";
            const products = await getProducts();
            let htmlString = `<thead>
                <tr>
                    <th>Nomor</th>
                    <th>Ketersediaan</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>`;

            products.forEach((item) => {
                htmlString += `<tr>
                    <td>${item.fields.nomor}</td>
                    <td>${item.fields.ketersediaan}</td>
                    <td>
						<a href="${baseUrl.replace('0', item.pk)}">
							<button class="btn btn-primary">
								Rubah Status
							</button>
						</a>
					</td>
                </tr>`;
            });

            htmlString += `</tbody>`;
            table.innerHTML = htmlString;
        }

        refreshProducts();
		
        function addProduct() {
			const form = document.querySelector('#form');
			const formData = new FormData(form);
            fetch("{% url 'sistem_manajemen:add_ruangan_ajax' %}", {
                method: "POST",
                body: formData
            }).then(refreshProducts)

            document.getElementById("form").reset();
            return false;
        }

        document.getElementById("button_add").onclick = addProduct;
        
    </script>
{% endblock content %}