beranda/urls.py
from django.urls import path
from beranda.views import *

app_name = 'beranda'
urlpatterns = [
    path('', show_beranda, name='show_beranda'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path('peminjaman_buku/', show_peminjaman_buku, name='show_peminjaman_buku'),


]

book/urls.py
from django.urls import path
from book.views import get_books

app_name = 'book'
urlpatterns = [
    path("", get_books, name="get_books"),
]

peminjaman_buku/urls.py
from django.urls import path
from . import views
from .views import create_pinjam_buku

app_name = 'peminjaman_buku' 

urlpatterns = [
    path('pinjam-buku/<int:book_id>/', views.pinjam_buku, name='pinjam_buku'),
    path('pinjam_buku_list/', views.pinjam_buku_list, name='pinjam_buku_list'),
    path('show-detail/<int:book_id>/', views.show_detail, name='show_detail'),
    path('kembalikan_buku/<str:pinjam_buku_title>/', views.kembalikan_buku, name='kembalikan_buku'),
    path('create_pinjam_buku/', create_pinjam_buku, name='create_pinjam_buku'),
    path('list_buku_flutter/<str:uname>/', views.list_buku_flutter, name='list_buku_flutter'),

]

pustaring/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/books/', include("book.urls")),
    path('sistem_manajemen/', include("sistem_manajemen.urls")),
    path('fitur_premium/', include("fitur_premium.urls")),
    path('customer_service/', include("customer_service.urls")),
    path('', include("beranda.urls")),
    path('ulasan/', include("ulasan.urls")),
    path('peminjaman_buku/', include("peminjaman_buku.urls")),
    path('auth/', include('authentication.urls')),
]

ulasan/urls.py
from django.urls import path
from peminjaman_buku.views import show_detail
from .views import create_review_flutter, get_user_review, show_peminjaman_buku, get_reviews_json, add_review_ajax, show_ulasan
from django.contrib.auth.views import LoginView

app_name = 'ulasan'

urlpatterns = [
    path('detail/<int:book_id>/', show_detail, name='show_detail'),
    path('peminjaman_buku/', show_peminjaman_buku, name='show_peminjaman_buku'),
    path('show-ulasan/<int:book_id>', show_ulasan, name ='show_ulasan'),
    path('get-reviews-json/<int:book_id>/', get_reviews_json, name='get_reviews_json'),
    path('get-user-reviews/<int:id>', get_user_review, name='get_user_review'),
    path('add-review-ajax/<int:book_id>/', add_review_ajax, name='add_review_ajax'),
    path('login/', LoginView.as_view(), name='login'),
    path('create-review-flutter/<int:id>/', create_review_flutter, name='create_review_flutter'),
]

ulasan/models.py
from django.db import models
from book.models import Book
# Create your models here.
class UserReview(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user_name = models.CharField(max_length=50)
    rating = models.IntegerField()
    review_text = models.TextField()
    date_added = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return f"Review by {self.user_name} for {self.book.title}"

ulasan/forms.py
from django.forms import ModelForm
from ulasan.models import UserReview

class BookForm(ModelForm):
    class Meta:
        model = UserReview
        fields = ['user_name', 'rating', 'review_text'] 

ulasan/views.py
import json
from django.shortcuts import get_object_or_404, render
from ulasan.forms import BookForm
from ulasan.models import UserReview
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound
from book.models import Book

# Create your views here.

def show_peminjaman_buku(request):
    books = Book.objects.filter(ketersediaan='tersedia')

    context = {
        'books': books,
    }
    
    return render(request,'peminjaman_buku.html', context)

def show_detail(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    return render(request, 'detail_buku.html', {'book': book})

def show_ulasan(request, book_id):
    book = Book.objects.get(pk=book_id)
    reviews = UserReview.objects.filter(book=book)
    form = BookForm()

    context = {
        'page': 'Reviews',
        'reviews': reviews,
        'book': book,
        'form': form,
    }

    return render(request, "ulasan_buku.html", context)

def get_reviews_json(request, book_id):
    book = Book.objects.get(pk=book_id)
    reviews = UserReview.objects.filter(book=book).values('user_name', 'rating', 'review_text', 'date_added')
    return JsonResponse(list(reviews), safe= False)

def get_user_review(request,id):
    book = Book.objects.get(pk=id)
    reviews = UserReview.objects.filter (book= book, user_name = request.user).values('user_name', 'rating', 'review_text', 'date_added')
    return JsonResponse(list(reviews), safe = False)


@csrf_exempt
def add_review_ajax(request, book_id):
    if request.method == 'POST':
        user_name = request.user.username if request.user.is_authenticated else "AnonymousUser"
        rating = request.POST.get("rating")
        review_text = request.POST.get("review_text")
        book = get_object_or_404(Book, id=book_id)

        try:
            # Memastikan nilai rating berada dalam rentang yang valid (misalnya, antara 1 dan 5)
            if rating is not None:
                rating = int(rating)
                if 1 <= rating <= 5:
                    # Proses penyimpanan ulasan ke database
                    review = UserReview.objects.create(
                        book=book,
                        user_name=user_name,
                        rating=rating,
                        review_text=review_text,
                    )
                    return HttpResponse(b"CREATED", status=201)
                else:
                    return JsonResponse({'status': 'error', 'message': 'Rating harus berada dalam rentang 1 hingga 5.'})
            else:
                return JsonResponse({'status': 'error', 'message': 'Rating tidak boleh kosong.'})
        except ValueError:
            return JsonResponse({'status': 'error', 'message': 'Rating harus berupa angka.'})
    else:
        return HttpResponseNotFound()

@csrf_exempt
def create_review_flutter(request, id):
    if request.method == 'POST':
        data = json.loads(request.body)

        user_name = request.user.username if request.user.is_authenticated else "AnonymousUser"
        rating = data.get("rating")
        review_text = data.get("review_text")
        book = get_object_or_404(Book, id=id)

        try:
            # Perform any necessary validation on the data here
            # ...

            # Create a new UserReview instance
            review = UserReview.objects.create(
                book=book,
                user_name=user_name,
                rating=int(rating),
                review_text=review_text,
            )

            return JsonResponse({"status": "success"}, status=201)

        except KeyError:
            return JsonResponse({'status': 'error', 'message': 'Invalid data format.'}, status=400)
        except ValueError:
            return JsonResponse({'status': 'error', 'message': 'Invalid data format or values.'}, status=400)

    else:
        return HttpResponseNotFound()

ulasan/templates/detail_buku.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">Informasi Buku</h1>
                <h2>Judul: {{ book.title }}</h2>
                <h3>Genre: {{ book.genre }}</h3>
                {% if book.ketersediaan %}
                    <h3>Ketersediaan: Tersedia </h3>
                {% else %}
                    <h3>Ketersediaan: Tidak tersedia </h3>
                {% endif %}
                <p>Ringkasan: {{ book.summary }}</p>
                
                <a href="{% url 'beranda:show_peminjaman_buku' %}">
                    <button class="btn btn-secondary">
                        Back
                    </button>
                </a>
                <a href="{% url 'ulasan:show_ulasan' book.id %}">
                    <button class="btn btn-primary">
                        Lihat Ulasan
                    </button>
                </a>
            </div>
        </div>
    </div>
{% endblock content %}

ulasan/templates/ulasan_buku.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">Ulasan Buku</h1>
                <h2>Judul Buku: {{ book.title }}</h2>

                <!-- Daftar Ulasan Pengguna -->
                <h3>Ulasan Pengguna: </h3>
                <div class="row" id="user-reviews"></div>

                <!-- Tombol kembali ke Detail Buku -->
                <a href="{% url 'peminjaman_buku:show_detail' book.id %}">
                    <button class="btn btn-secondary">Back</button>
                </a>

                <!-- Tombol untuk menambah ulasan menggunakan AJAX -->
                <button type="button" class="btn custom-btn-color" id="add-review-ajax" data-bs-toggle="modal" data-bs-target="#reviewModal" style="background-color: #345941; color: #ffffff; padding: 5px 15px; border: none; border-radius: 5px; margin-right: 5px;">
                    Add Review by AJAX
                </button>
            </div>
        </div>

        <!-- Formulir untuk menambahkan ulasan menggunakan modal -->
        <div class="modal fade" id="reviewModal" tabindex="-1" aria-labelledby="reviewModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="reviewModalLabel">Tambahkan Ulasan Anda</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        
                        <form id="review_form_modal">
                            {% csrf_token %}
                            <p>Oleh: {{ request.user.username }}</p>
                            <label for="rating_modal">Rating:</label>
                            <select id="rating_modal" name="rating" required>
                                <option value="5">★★★★★</option>
                                <option value="4">★★★★☆</option>
                                <option value="3">★★★☆☆</option>
                                <option value="2">★★☆☆☆</option>
                                <option value="1">★☆☆☆☆</option>
                            </select>
                            <label for="review_text_modal">Ulasan Anda:</label>
                            <textarea id="review_text_modal" name="review_text" required></textarea>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                        {% if request.user.is_authenticated %}
                            <button type="button" class="btn btn-primary" id="submit_review" data-bs-dismiss="modal">Kirim Ulasan</button>
                        {% else %}
                            <a href="{% url 'beranda:login' %}" class="btn btn-primary">Login untuk menambahkan ulasan</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>


        <script>
            
            // Fungsi untuk mendapatkan ulasan buku
            async function getReviews() {
                let url = `{% url 'ulasan:get_reviews_json' book.id %}`;
                return fetch(url).then((res) => res.json());
            }
            
            async function getUserReviews() {
                const userReviews = fetch("{% url 'ulasan:get_user_review' book.pk %}").then((res) => res.json());
                console.log(userReviews)

                return userReviews;
            }
            // Fungsi untuk menampilkan ulasan buku
            async function refreshReviews() {
                const reviewsContainer = document.getElementById("user-reviews");
                reviewsContainer.innerHTML = '';

                const reviews = await getReviews();

                if (reviews.length === 0) {
                    // If no reviews are available, display a message
                    const noReviewMessage = document.createElement('p');
                    noReviewMessage.textContent = 'Ulasan belum tersedia';
                    reviewsContainer.appendChild(noReviewMessage);
                } else {
                    // If there are reviews, display each review in a card
                    reviews.forEach((review) => {
                        const starRating = generateStarRating(review.rating);

                        // Create a card for each review
                        const cardDiv = document.createElement('div');
                        cardDiv.classList.add('card', 'mb-3');
                        const cardBodyDiv = document.createElement('div');
                        cardBodyDiv.classList.add('card-body');

                        // Populate the card body with content
                        cardBodyDiv.innerHTML = `
                            <p><strong>Oleh:</strong> ${review.user_name}</p>
                            <p><strong>Rating:</strong> ${starRating} (${review.rating} stars)</p>
                            <p><strong>Ulasan:</strong> ${review.review_text}</p>
                            <p><strong>Date Added:</strong> ${review.date_added}</p>
                        `;

                        // Append the card body to the card
                        cardDiv.appendChild(cardBodyDiv);

                        // Append the card to the container
                        reviewsContainer.appendChild(cardDiv);
                    });
                }
            }
            refreshReviews()

            function addReview() {
                getUserReviews().then((reviews) => {
                    if (reviews.length > 0) {
                        alert("Anda sudah memberikan ulasan untuk buku ini.");
                        document.getElementById("review_form_modal").reset();
                    } else {
                        fetch("{% url 'ulasan:add_review_ajax' book.id %}", {
                            method: "POST",
                            body: new FormData(document.querySelector('#review_form_modal'))
                        }).then((response) => {
                            if (response.ok) {
                                // Review added successfully, refresh reviews
                                refreshReviews();
                                document.getElementById("review_form_modal").reset();
                            } else {
                                // Handle the case when review submission fails
                                alert("Gagal menambahkan ulasan. Silakan coba lagi.");
                            }
                        });
                    }
                });

                return false;
            }

            document.getElementById("submit_review").onclick = addReview
          
    
        
            function generateStarRating(starCount) {
                const filledStars = '<i class="fa fa-star"></i>'.repeat(starCount);
                const emptyStars = '<i class="fa fa-star-o"></i>'.repeat(5 - starCount);
                return filledStars + emptyStars;
            }

            
        </script>
        
{% endblock content %}