book/urls.py
from django.urls import path
from book.views import get_books

app_name = 'book'
urlpatterns = [
    path("", get_books, name="get_books"),
]

customer_service/urls.py
from django.urls import path
from customer_service.views import *

app_name = 'customer_service'
urlpatterns = [
    path('', show_customer_service, name='show_customer_service'),
    path('add_report/', add_report, name='add_report'),
    path('add_complaint/', add_complaint, name='add_complaint'),
    path('get_reports_json', get_reports_json, name='get_reports_json'),
    path('get_all_reports_json', get_all_reports_json, name='get_all_reports_json'),
    path('get_books_json_by_ids/', get_books_json_by_ids, name='get_books_json_by_ids'),
    path('json/', show_json, name='show_json'),
    path('confirm_report/', confirm_report, name='confirm_report'),
    path('finish_report/', finish_report, name='finish_report'),
    path('customer_servicer', show_customer_service, name='show_customer_servicer'),
]

pustaring/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/books/', include("book.urls")),
    path('sistem_manajemen/', include("sistem_manajemen.urls")),
    path('fitur_premium/', include("fitur_premium.urls")),
    path('customer_service/', include("customer_service.urls")),
    path('', include("beranda.urls")),
    path('ulasan/', include("ulasan.urls")),
    path('peminjaman_buku/', include("peminjaman_buku.urls")),
    path('auth/', include('authentication.urls')),
]

customer_service/models.py
import json
from django.db import models
from book.models import Book
from sistem_manajemen.models import Ruangan
from django.contrib.auth.models import User

class Report(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    losts = models.TextField(blank=True, null=True)
    brokens = models.TextField(blank=True, null=True)
    report_date = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=12)
    message = models.TextField()

    def set_losts(self, losts):
        self.losts = json.dumps(losts)

    def get_losts(self):
        return json.loads(self.losts)

    def set_brokens(self, brokens):
        self.brokens = json.dumps(brokens)

    def get_brokens(self):
        return json.loads(self.brokens)

    def set_status(self, new_status):
        self.status = new_status

    def set_message(self, new_message):
        self.message = new_message

class Complaint(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.TextField()
    report_date = models.DateField(auto_now_add=True)

customer_service/views.py
import datetime
import json
from book.models import Book
from peminjaman_buku.models import PinjamBuku
from customer_service.models import Report, Complaint
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User

@login_required(login_url='/login')
def show_customer_service(request):
    context = {'borrowed': PinjamBuku.objects.filter(pengguna=request.user)}
    return render(request, "customer_service.html", context)

def show_customer_servicer(request):
    return render(request, "customer_servicer.html", {})

def get_all_reports_json(request):
    reports = Report.objects.all()
    return HttpResponse(serializers.serialize('json', reports))

def get_reports_json(request):
    reports = Report.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', reports))

def get_books_json_by_ids(request, ids):
    books = Book.objects.filter(pk__in=ids)
    return HttpResponse(serializers.serialize('json', books))

@csrf_exempt
def add_report(request):
    if request.method == 'POST':
        user = request.user
        data = json.loads(request.body)
        losts = data.get('losts', [])
        brokens = data.get('brokens', [])
        status = 'REQUESTED'
        message = 'Diajukan'
        new_report = Report(user=user, status=status, message=message)
        new_report.set_losts(losts)
        new_report.set_brokens(brokens)
        new_report.save()
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def confirm_report(request, id):
    if request.method == 'POST':
        report = Report.objects.filter(pk=id)
        report.set_status('CONFIRMED')
        report.set_message('Dikonformasi, menunggu pembayaran denda')
        report.save()
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def finish_report(request, id):
    if request.method == 'POST':
        report = Report.objects.filter(pk=id)
        report.set_status('DONE')
        report.set_message('Laporan selesai')
        report.save()
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

def add_complaint(request):
    if request.method == 'POST':
        user = request.user
        description = request.POST.get("description")
        new_complaint = Complaint(user=user, description=description)
        new_complaint.save()
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

def show_json(request):
    data = Report.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

customer_service/templates/customer_service.html
{% extends 'base.html' %} {% block content %}
<h1>Bantuan</h1>
<div id="reports"></div>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#bookReportModal">Laporan</button>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#complaintModal">Aduan/Saran</button>
<div class="modal fade" id="bookReportModal" tabindex="-1" aria-labelledby="bookReportModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="bookReportModalLabel">Laporan Buku</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %} {% for book in borrowed.book reversed %}
                    <div class="card border-primary mb-3" style="max-width: 18rem;">
                        <div class="card-body text-primary">
                            <h5 class="card-title">{{book.title}}</h5>
                            <p class="card-text">
                                Tangal Peminjaman: {{borrowed.tanggal_peminjaman}}
                            </p>
                            <select class="status" id={{book.pk}}>
                                <option value="">Opsi</option>
                                <option value="broken">Rusak</option>
                                <option value="lost">Hilang</option>
                            </select>
                        </div>
                    </div>
                    {% endfor %}
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Buat Laporan</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="complaintModal" tabindex="-1" aria-labelledby="complaintModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="complaintModalLabel">Aduan/Saran</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <textarea class="form-control" id="description" name="description" value="Deskripsi"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Buat Aduan/Saran</button>
            </div>
        </div>
    </div>
</div>

<script>
    async function getReports() {
        return fetch("{% url 'customer_service:get_reports_json' %}").then((res) => res.json())
    }

    async function getBooksByIds(ids) {
        return fetch(`{% url 'customer_service:get_books_json_by_ids' %}?ids=ids`).then((res) => res.json());
    }

    async function refreshReports() {
        document.getElementById("reports").innerHTML = ""
        const reports = await getReports()
        let htmlString = ``
        reports.forEach((report) => {
            htmlString += `\n<div class="card border-primary mb-3" style="width: 12rem; text-align: center">
                <div class="card-body text-primary">
                    <h5 class="card-title">Laporan ${report.pk}</h5>
                    <h7 class="card-text">${report.fields.report_date}</h7>
                    <p class="card-text">${report.fields.message}</p>
                </div>
            </div>`
        })
        document.getElementById("reports").innerHTML = htmlString
    }
    refreshReports()

    function addReport() {
        var losts = [];
        var brokens = [];
        var selectElements = document.querySelectorAll(".status");
        selectElements.forEach(function(select) {
            if (select.value === "lost") {
                losts.push(parseInt(select.id));
            } else if (select.value === "broken") {
                brokens.push(parseInt(select.id));
            }
        });
        if (losts.length === 0 && brokens.length === 0) {
            $('#bookReportModal').modal('hide');
            return false;
        }
        fetch("{% url 'customer_service:add_report' %}", {
            method: "POST",
            body: JSON.stringify({
                brokens: brokens,
                losts: losts
            })
        }).then(refreshReports)
        document.getElementById("form").reset()
        return false
    }
    document.getElementById("button_add").onclick = addReport
</script>{% endblock content %}

customer_service/templates/customer_servicer.html
{% extends 'base.html' %} {% block content %}

<h1>Laporan</h1>
<div id="reports"></div>

<script>
    async function getReports() {
        return fetch("{% url 'customer_service:get_all_reports_json' %}").then((res) => res.json())
    }

    async function refreshReports() {
        document.getElementById("reports").innerHTML = ""
        const reports = await getReports()
        let htmlString = ``
        reports.forEach((report) => {
            htmlString += `\n<div class="card border-primary mb-3" style="width: 12rem; text-align: center">
                <div class="card-body text-primary">
                    <h5 class="card-title">${report.user.username}</h5>
                    <h6 class="card-text">Laporan ${report.pk}</h6>
                    <h7 class="card-text">${report.fields.report_date}</h7>`
            if (report.fields.status === 'REQUESTED') {
                htmlString += `\n        <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal" onClick="confirm(${report.pk})">Konfirmasi</button>`
            } else if (report.fields.status === 'CONFIRMED') {
                htmlString += `\n        <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal onClick="finish(${report.pk})">Selesai</button>`
            }
            htmlString += `\n    </div>
            </div>`
        })
        document.getElementById("reports").innerHTML = htmlString
    }
    refreshReports()

    async function confirm(id) {
        fetch("{% url 'customer_service:confirm_report'?id=${id} %}", {
            method: POST
        })
        refreshReports()
    }

    async function finish(id) {
        fetch("{% url 'customer_service:finish_report'?id=${id} %}", {
            method: POST
        })
        refreshReports()
    }
</script>

{% endblock content %}